# Generated by Django 4.2.9 on 2024-04-04 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='gantt_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='location_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('related_ids', models.CharField(max_length=50)),
                ('franchiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
