# Generated by Django 4.2.9 on 2024-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_local_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='location_found',
        ),
        migrations.AddField(
            model_name='partner',
            name='tasks',
            field=models.ManyToManyField(related_name='partners', to='api.task'),
        ),
    ]
