# Generated by Django 4.2.9 on 2024-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_task_related_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='partners', to='api.task'),
        ),
    ]
