# Generated by Django 4.2.9 on 2024-04-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_partner_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_ids',
        ),
        migrations.AddField(
            model_name='task',
            name='parents',
            field=models.ManyToManyField(blank=True, to='api.task'),
        ),
    ]
