# Generated by Django 4.2.9 on 2024-05-04 00:27

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_task_description_remove_task_related_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField()),
                ('finished', models.BooleanField()),
                ('access_code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyles', to='api.partner')),
            ],
        ),
    ]
