# Generated by Django 4.2.9 on 2024-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.partner'),
        ),
    ]
