# Generated by Django 4.2.9 on 2024-05-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_analysis_template_name_analysis_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='template',
            new_name='is_template',
        ),
    ]
